# Generated by Django 5.2.7 on 2025-10-13 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appModels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='dtime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homework',
            name='dtime_edit',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения'),
        ),
        migrations.AddField(
            model_name='homework',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус публикации'),
        ),
    ]
