# Generated by Django 5.2.7 on 2025-11-01 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appModels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название услуги')),
            ],
            options={
                'verbose_name': 'услугу',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(verbose_name='Адрес')),
                ('dtime', models.DateTimeField(verbose_name='Дата и время')),
                ('method_pay', models.CharField(choices=[('Наличные', 'Наличные'), ('Карта', 'Карта')], default='Наличные', max_length=120, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('В работе', 'В работе'), ('Выполнено', 'Выполнено'), ('Отменено', 'Отменено')], default='В работе', max_length=120, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appModels.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
