# Generated by Django 5.2.6 on 2025-09-22 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appModels', '0002_course_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterField(
            model_name='course',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.BooleanField(choices=[(True, 'Опубликован'), (False, 'Не опубликован')], default=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.BooleanField(choices=[(True, 'Опубликован'), (False, 'Не опубликован')], default=True, verbose_name='Статус')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appModels.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'тема',
                'verbose_name_plural': 'Темы',
            },
        ),
    ]
