# Generated by Django 5.2.6 on 2025-09-22 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appModels', '0003_alter_course_options_alter_course_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'тему', 'verbose_name_plural': 'Темы'},
        ),
    ]
