# Generated by Django 5.2.6 on 2025-09-23 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appModels', '0004_alter_topic_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.BooleanField(choices=[(True, 'Опубликован'), (False, 'Не опубликовано')], default=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.BooleanField(choices=[(True, 'Опубликован'), (False, 'Не опубликовано')], default=True, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.BooleanField(choices=[(True, 'Опубликован'), (False, 'Не опубликовано')], default=True, verbose_name='Статус')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appModels.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'подтему',
                'verbose_name_plural': 'Подтемы',
            },
        ),
    ]
